server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.193.131:8761/eureka
  instance:
    hostname: order-service

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.193.131/demo_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    
env: dev
